export const GENRES = {
  sci_fi: "Sci-Fi",
  epic: "Epic",
  drama: "Drama",
  adventure: "Adventure",
  superhero: "Superhero",
  horror: "Horror",
  crime: "Crime",
  biography: "Biography",
  history: "History",
  musical: "Musical",
  animation: "Animation",
  biographical: "Biographical",
  family: "Family",
  animated: "Animated",
  neo_noir: "Neo Noir",
  romance: "Romance",
  action: "Action",
  comedy: "Comedy",
  thriller: "Thriller",
  mystery: "Mystery",
  fantasy: "Fantasy",
  historical: "Historical",
  sports: "Sports",
  western: "Western",
  disaster: "Disaster",
};