const IMG = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop";

export const PEOPLE = [
  // ── DIRECTORS & WRITERS ───────────────────────────────────────────────────
  { id: "christopher_nolan", name: "Christopher Nolan", roles: ["Director", "Writer", "Producer"], image: IMG },
  { id: "denis_villeneuve", name: "Denis Villeneuve", roles: ["Director", "Writer"], image: IMG },
  { id: "francis_ford_coppola", name: "Francis Ford Coppola", roles: ["Director", "Writer"], image: IMG },
  { id: "steven_spielberg", name: "Steven Spielberg", roles: ["Director", "Producer"], image: IMG },
  { id: "frank_darabont", name: "Frank Darabont", roles: ["Director", "Writer"], image: IMG },
  { id: "robert_zemeckis", name: "Robert Zemeckis", roles: ["Director"], image: IMG },
  { id: "quentin_tarantino", name: "Quentin Tarantino", roles: ["Director", "Writer"], image: IMG },
  { id: "jonathan_demme", name: "Jonathan Demme", roles: ["Director"], image: IMG },
  { id: "martin_scorsese", name: "Martin Scorsese", roles: ["Director", "Writer", "Producer"], image: IMG },
  { id: "david_fincher", name: "David Fincher", roles: ["Director"], image: IMG },
  { id: "lilly_wachowski", name: "Lilly Wachowski", roles: ["Director", "Writer"], image: IMG },
  { id: "lana_wachowski", name: "Lana Wachowski", roles: ["Director", "Writer"], image: IMG },
  { id: "james_cameron", name: "James Cameron", roles: ["Director", "Writer"], image: IMG },
  { id: "stanley_kubrick", name: "Stanley Kubrick", roles: ["Director", "Writer"], image: IMG },
  { id: "ridley_scott", name: "Ridley Scott", roles: ["Director", "Producer"], image: IMG },
  { id: "roger_allers", name: "Roger Allers", roles: ["Director"], image: IMG },
  { id: "rob_minkoff", name: "Rob Minkoff", roles: ["Director"], image: IMG },
  { id: "ramesh_sippy", name: "Ramesh Sippy", roles: ["Director"], image: IMG },
  { id: "alejandro_gonzalez_inarritu", name: "Alejandro González Iñárritu", roles: ["Director", "Writer"], image: IMG },
  { id: "peter_jackson", name: "Peter Jackson", roles: ["Director", "Writer"], image: IMG },
  { id: "ron_howard", name: "Ron Howard", roles: ["Director"], image: IMG },
  { id: "hayao_miyazaki", name: "Hayao Miyazaki", roles: ["Director", "Writer"], image: IMG },
  { id: "fernando_meirelles", name: "Fernando Meirelles", roles: ["Director"], image: IMG },
  { id: "katia_lund", name: "Kátia Lund", roles: ["Director"], image: IMG },
  { id: "park_chan_wook", name: "Park Chan-wook", roles: ["Director", "Writer"], image: IMG },
  { id: "michel_gondry", name: "Michel Gondry", roles: ["Director", "Writer"], image: IMG },
  { id: "clint_eastwood", name: "Clint Eastwood", roles: ["Director", "Actor", "Composer"], image: IMG },
  { id: "ang_lee", name: "Ang Lee", roles: ["Director"], image: IMG },
  { id: "guillermo_del_toro", name: "Guillermo del Toro", roles: ["Director", "Writer"], image: IMG },
  { id: "joel_coen", name: "Joel Coen", roles: ["Director", "Writer"], image: IMG },
  { id: "ethan_coen", name: "Ethan Coen", roles: ["Director", "Writer"], image: IMG },
  { id: "paul_thomas_anderson", name: "Paul Thomas Anderson", roles: ["Director", "Writer"], image: IMG },
  { id: "danny_boyle", name: "Danny Boyle", roles: ["Director"], image: IMG },
  { id: "loveleen_tandan", name: "Loveleen Tandan", roles: ["Director"], image: IMG },
  { id: "florian_henckel_von_donnersmarck", name: "Florian Henckel von Donnersmarck", roles: ["Director", "Writer"], image: IMG },
  { id: "pete_docter", name: "Pete Docter", roles: ["Director", "Writer"], image: IMG },
  { id: "bob_peterson", name: "Bob Peterson", roles: ["Director", "Writer", "Actor"], image: IMG },
  { id: "lee_unkrich", name: "Lee Unkrich", roles: ["Director", "Writer"], image: IMG },
  { id: "darren_aronofsky", name: "Darren Aronofsky", roles: ["Director"], image: IMG },
  { id: "asghar_farhadi", name: "Asghar Farhadi", roles: ["Director", "Writer"], image: IMG },
  { id: "nicolas_winding_refn", name: "Nicolas Winding Refn", roles: ["Director"], image: IMG },
  { id: "olivier_nakache", name: "Olivier Nakache", roles: ["Director", "Writer"], image: IMG },
  { id: "eric_toledano", name: "Éric Toledano", roles: ["Director", "Writer"], image: IMG },
  { id: "alfonso_cuaron", name: "Alfonso Cuarón", roles: ["Director", "Writer"], image: IMG },
  { id: "steve_mcqueen", name: "Steve McQueen", roles: ["Director"], image: IMG },
  { id: "damien_chazelle", name: "Damien Chazelle", roles: ["Director", "Writer"], image: IMG },
  { id: "george_miller", name: "George Miller", roles: ["Director", "Writer"], image: IMG },
  { id: "kenneth_lonergan", name: "Kenneth Lonergan", roles: ["Director", "Writer"], image: IMG },
  { id: "jordan_peele", name: "Jordan Peele", roles: ["Director", "Writer"], image: IMG },
  { id: "adrian_molina", name: "Adrian Molina", roles: ["Director", "Writer"], image: IMG },
  { id: "john_krasinski", name: "John Krasinski", roles: ["Director", "Writer", "Actor"], image: IMG },
  { id: "bob_persichetti", name: "Bob Persichetti", roles: ["Director"], image: IMG },
  { id: "anthony_russo", name: "Anthony Russo", roles: ["Director"], image: IMG },
  { id: "bong_joon_ho", name: "Bong Joon-ho", roles: ["Director", "Writer"], image: IMG },
  { id: "todd_phillips", name: "Todd Phillips", roles: ["Director", "Writer"], image: IMG },
  { id: "kemp_powers", name: "Kemp Powers", roles: ["Director", "Writer"], image: IMG },
  { id: "lee_isaac_chung", name: "Lee Isaac Chung", roles: ["Director", "Writer"], image: IMG },
  { id: "jane_campion", name: "Jane Campion", roles: ["Director", "Writer"], image: IMG },
  { id: "jon_watts", name: "Jon Watts", roles: ["Director"], image: IMG },
  { id: "daniel_kwan", name: "Daniel Kwan", roles: ["Director", "Writer"], image: IMG },
  { id: "joseph_kosinski", name: "Joseph Kosinski", roles: ["Director"], image: IMG },
  { id: "martin_mcdonagh", name: "Martin McDonagh", roles: ["Director", "Writer"], image: IMG },
  { id: "edward_berger", name: "Edward Berger", roles: ["Director", "Writer"], image: IMG },
  { id: "celine_song", name: "Celine Song", roles: ["Director", "Writer"], image: IMG },
  { id: "yorgos_lanthimos", name: "Yorgos Lanthimos", roles: ["Director"], image: IMG },
  { id: "greta_gerwig", name: "Greta Gerwig", roles: ["Director", "Writer"], image: IMG },
  { id: "coralie_fargeat", name: "Coralie Fargeat", roles: ["Director", "Writer"], image: IMG },
  { id: "ashutosh_gowariker", name: "Ashutosh Gowariker", roles: ["Director", "Writer"], image: IMG },
  { id: "farhan_akhtar", name: "Farhan Akhtar", roles: ["Director", "Writer"], image: IMG },
  { id: "aditya_chopra", name: "Aditya Chopra", roles: ["Director", "Writer"], image: IMG },
  { id: "k_asif", name: "K. Asif", roles: ["Director"], image: IMG },
  { id: "rajkumar_hirani", name: "Rajkumar Hirani", roles: ["Director", "Writer"], image: IMG },
  { id: "nitesh_tiwari", name: "Nitesh Tiwari", roles: ["Director", "Writer"], image: IMG },
  { id: "s_s_rajamouli", name: "S. S. Rajamouli", roles: ["Director", "Writer"], image: IMG },
  { id: "aamir_khan", name: "Aamir Khan", roles: ["Director", "Actor", "Producer"], image: IMG },
  { id: "prashanth_neel", name: "Prashanth Neel", roles: ["Director", "Writer"], image: IMG },
  { id: "rishab_shetty", name: "Rishab Shetty", roles: ["Director", "Writer", "Actor"], image: IMG },
  { id: "atlee", name: "Atlee", roles: ["Director", "Writer"], image: IMG },
  { id: "sriram_raghavan", name: "Sriram Raghavan", roles: ["Director", "Writer"], image: IMG },
  { id: "zoya_akhtar", name: "Zoya Akhtar", roles: ["Director", "Writer"], image: IMG },
  { id: "sanjay_leela_bhansali", name: "Sanjay Leela Bhansali", roles: ["Director"], image: IMG },
  { id: "jean_pierre_jeunet", name: "Jean-Pierre Jeunet", roles: ["Director", "Writer"], image: IMG },
  { id: "thomas_vinterberg", name: "Thomas Vinterberg", roles: ["Director", "Writer"], image: IMG },
  { id: "paolo_sorrentino", name: "Paolo Sorrentino", roles: ["Director", "Writer"], image: IMG },
  { id: "laszlo_nemes", name: "László Nemes", roles: ["Director", "Writer"], image: IMG },
  { id: "ruben_ostlund", name: "Ruben Östlund", roles: ["Director", "Writer"], image: IMG },
  { id: "nadine_labaki", name: "Nadine Labaki", roles: ["Director", "Writer"], image: IMG },
  { id: "ryusuke_hamaguchi", name: "Ryūsuke Hamaguchi", roles: ["Director", "Writer"], image: IMG },

  { id: "jon_spaihts", name: "Jon Spaihts", roles: ["Writer"], image: IMG },
  { id: "jonathan_nolan", name: "Jonathan Nolan", roles: ["Writer"], image: IMG },
  { id: "mario_puzo", name: "Mario Puzo", roles: ["Writer"], image: IMG },
  { id: "steven_zaillian", name: "Steven Zaillian", roles: ["Writer"], image: IMG },
  { id: "eric_roth", name: "Eric Roth", roles: ["Writer"], image: IMG },
  { id: "roger_avary", name: "Roger Avary", roles: ["Writer"], image: IMG },
  { id: "ted_tally", name: "Ted Tally", roles: ["Writer"], image: IMG },
  { id: "nicholas_pileggi", name: "Nicholas Pileggi", roles: ["Writer"], image: IMG },
  { id: "jim_uhls", name: "Jim Uhls", roles: ["Writer"], image: IMG },
  { id: "arthur_c_clarke", name: "Arthur C. Clarke", roles: ["Writer"], image: IMG },
  { id: "david_franzoni", name: "David Franzoni", roles: ["Writer"], image: IMG },
  { id: "john_logan", name: "John Logan", roles: ["Writer"], image: IMG },
  { id: "william_nicholson", name: "William Nicholson", roles: ["Writer"], image: IMG },
  { id: "irene_mecchi", name: "Irene Mecchi", roles: ["Writer"], image: IMG },
  { id: "jonathan_roberts", name: "Jonathan Roberts", roles: ["Writer"], image: IMG },
  { id: "linda_woolverton", name: "Linda Woolverton", roles: ["Writer"], image: IMG },
  { id: "salim_khan", name: "Salim Khan", roles: ["Writer"], image: IMG },
  { id: "javed_akhtar", name: "Javed Akhtar", roles: ["Writer", "Composer"], image: IMG },
  { id: "guillermo_arriaga", name: "Guillermo Arriaga", roles: ["Writer"], image: IMG },
  { id: "fran_walsh", name: "Fran Walsh", roles: ["Writer"], image: IMG },
  { id: "philippa_boyens", name: "Philippa Boyens", roles: ["Writer"], image: IMG },
  { id: "akiva_goldsman", name: "Akiva Goldsman", roles: ["Writer"], image: IMG },
  { id: "stephen_sinclair", name: "Stephen Sinclair", roles: ["Writer"], image: IMG },
  { id: "braulio_mantovani", name: "Bráulio Mantovani", roles: ["Writer"], image: IMG },
  { id: "jeff_nathanson", name: "Jeff Nathanson", roles: ["Writer"], image: IMG },
  { id: "hwang_jo_yoon", name: "Hwang Jo-yoon", roles: ["Writer"], image: IMG },
  { id: "lim_chun_hyeong", name: "Lim Chun-hyeong", roles: ["Writer"], image: IMG },
  { id: "charlie_kaufman", name: "Charlie Kaufman", roles: ["Writer"], image: IMG },
  { id: "paul_haggis", name: "Paul Haggis", roles: ["Writer"], image: IMG },
  { id: "david_s_goyer", name: "David S. Goyer", roles: ["Writer"], image: IMG },
  { id: "larry_mcmurtry", name: "Larry McMurtry", roles: ["Writer"], image: IMG },
  { id: "diana_ossana", name: "Diana Ossana", roles: ["Writer"], image: IMG },
  { id: "william_monahan", name: "William Monahan", roles: ["Writer"], image: IMG },
  { id: "simon_beaufoy", name: "Simon Beaufoy", roles: ["Writer"], image: IMG },
  { id: "michael_arndt", name: "Michael Arndt", roles: ["Writer"], image: IMG },
  { id: "mark_heyman", name: "Mark Heyman", roles: ["Writer"], image: IMG },
  { id: "andres_heinz", name: "Andres Heinz", roles: ["Writer"], image: IMG },
  { id: "john_mclaughlin", name: "John McLaughlin", roles: ["Writer"], image: IMG },
  { id: "hossein_amini", name: "Hossein Amini", roles: ["Writer"], image: IMG },
  { id: "david_magee", name: "David Magee", roles: ["Writer"], image: IMG },
  { id: "jonas_cuaron", name: "Jonás Cuarón", roles: ["Writer"], image: IMG },
  { id: "john_ridley", name: "John Ridley", roles: ["Writer"], image: IMG },
  { id: "terence_winter", name: "Terence Winter", roles: ["Writer"], image: IMG },
  { id: "nicolas_giacobone", name: "Nicolás Giacobone", roles: ["Writer"], image: IMG },
  { id: "alexander_dinelaris_jr", name: "Alexander Dinelaris Jr.", roles: ["Writer"], image: IMG },
  { id: "armando_bo", name: "Armando Bo", roles: ["Writer"], image: IMG },
  { id: "brendan_mccarthy", name: "Brendan McCarthy", roles: ["Writer"], image: IMG },
  { id: "nico_lathouris", name: "Nico Lathouris", roles: ["Writer"], image: IMG },
  { id: "mark_l_smith", name: "Mark L. Smith", roles: ["Writer"], image: IMG },
  { id: "eric_heisserer", name: "Eric Heisserer", roles: ["Writer"], image: IMG },
  { id: "hampton_fancher", name: "Hampton Fancher", roles: ["Writer"], image: IMG },
  { id: "michael_green", name: "Michael Green", roles: ["Writer"], image: IMG },
  { id: "matthew_aldrich", name: "Matthew Aldrich", roles: ["Writer"], image: IMG },
  { id: "bryan_woods", name: "Bryan Woods", roles: ["Writer"], image: IMG },
  { id: "scott_beck", name: "Scott Beck", roles: ["Writer"], image: IMG },
  { id: "phil_lord", name: "Phil Lord", roles: ["Writer"], image: IMG },
  { id: "rodney_rothman", name: "Rodney Rothman", roles: ["Writer"], image: IMG },
  { id: "christopher_markus", name: "Christopher Markus", roles: ["Writer"], image: IMG },
  { id: "stephen_mcfeely", name: "Stephen McFeely", roles: ["Writer"], image: IMG },
  { id: "han_jin_won", name: "Han Jin-won", roles: ["Writer"], image: IMG },
  { id: "scott_silver", name: "Scott Silver", roles: ["Writer"], image: IMG },
  { id: "mike_jones", name: "Mike Jones", roles: ["Writer"], image: IMG },
  { id: "chris_mckenna", name: "Chris McKenna", roles: ["Writer"], image: IMG },
  { id: "erik_sommers", name: "Erik Sommers", roles: ["Writer"], image: IMG },
  { id: "daniel_scheinert", name: "Daniel Scheinert", roles: ["Writer"], image: IMG },
  { id: "ehren_kruger", name: "Ehren Kruger", roles: ["Writer"], image: IMG },
  { id: "eric_warren_singer", name: "Eric Warren Singer", roles: ["Writer"], image: IMG },
  { id: "christopher_mcquarrie", name: "Christopher McQuarrie", roles: ["Writer"], image: IMG },
  { id: "lesley_paterson", name: "Lesley Paterson", roles: ["Writer"], image: IMG },
  { id: "ian_stokell", name: "Ian Stokell", roles: ["Writer"], image: IMG },
  { id: "tony_mcnamara", name: "Tony McNamara", roles: ["Writer"], image: IMG },
  { id: "noah_baumbach", name: "Noah Baumbach", roles: ["Writer"], image: IMG },
  { id: "peter_straughan", name: "Peter Straughan", roles: ["Writer"], image: IMG },
  { id: "aman", name: "Aman", roles: ["Writer"], image: IMG },
  { id: "wajahat_mirza", name: "Wajahat Mirza", roles: ["Writer"], image: IMG },
  { id: "kamal_amrohi", name: "Kamal Amrohi", roles: ["Writer"], image: IMG },
  { id: "ehsan_rizvi", name: "Ehsan Rizvi", roles: ["Writer"], image: IMG },
  { id: "abhijat_joshi", name: "Abhijat Joshi", roles: ["Writer"], image: IMG },
  { id: "piyush_gupta", name: "Piyush Gupta", roles: ["Writer"], image: IMG },
  { id: "shreyas_jain", name: "Shreyas Jain", roles: ["Writer"], image: IMG },
  { id: "nikhil_mehrotra", name: "Nikhil Mehrotra", roles: ["Writer"], image: IMG },
  { id: "amole_gupte", name: "Amole Gupte", roles: ["Writer"], image: IMG },
  { id: "s_ramanagirivasan", name: "S. Ramanagirivasan", roles: ["Writer"], image: IMG },
  { id: "arijit_biswas", name: "Arijit Biswas", roles: ["Writer"], image: IMG },
  { id: "pooja_ladha_surti", name: "Pooja Ladha Surti", roles: ["Writer"], image: IMG },
  { id: "yogesh_chandekar", name: "Yogesh Chandekar", roles: ["Writer"], image: IMG },
  { id: "hemanth_rao", name: "Hemanth Rao", roles: ["Writer"], image: IMG },
  { id: "reema_kagti", name: "Reema Kagti", roles: ["Writer"], image: IMG },
  { id: "prakash_kapadia", name: "Prakash Kapadia", roles: ["Writer"], image: IMG },
  { id: "wang_hui_ling", name: "Wang Hui-Ling", roles: ["Writer"], image: IMG },
  { id: "james_schamus", name: "James Schamus", roles: ["Writer"], image: IMG },
  { id: "tsai_kuo_jung", name: "Tsai Kuo-Jung", roles: ["Writer"], image: IMG },
  { id: "guillaume_laurant", name: "Guillaume Laurant", roles: ["Writer"], image: IMG },
  { id: "tobias_lindholm", name: "Tobias Lindholm", roles: ["Writer"], image: IMG },
  { id: "umberto_contarello", name: "Umberto Contarello", roles: ["Writer"], image: IMG },
  { id: "clara_royer", name: "Clara Royer", roles: ["Writer"], image: IMG },
  { id: "jihad_hojeily", name: "Jihad Hojeily", roles: ["Writer"], image: IMG },
  { id: "michelle_keserwany", name: "Michelle Keserwany", roles: ["Writer"], image: IMG },
  { id: "georgina_abou_mrad", name: "Georgina Abou Mrad", roles: ["Writer"], image: IMG },
  { id: "takamasa_oe", name: "Takamasa Oe", roles: ["Writer"], image: IMG },

  // ── COMPOSERS ─────────────────────────────────────────────────────────────
  { id: "hans_zimmer", name: "Hans Zimmer", roles: ["Composer"], image: IMG },
  { id: "nino_rota", name: "Nino Rota", roles: ["Composer"], image: IMG },
  { id: "john_williams", name: "John Williams", roles: ["Composer"], image: IMG },
  { id: "thomas_newman", name: "Thomas Newman", roles: ["Composer"], image: IMG },
  { id: "alan_silvestri", name: "Alan Silvestri", roles: ["Composer"], image: IMG },
  { id: "howard_shore", name: "Howard Shore", roles: ["Composer"], image: IMG },
  { id: "the_dust_brothers", name: "The Dust Brothers", roles: ["Composer"], image: IMG },
  { id: "don_davis", name: "Don Davis", roles: ["Composer"], image: IMG },
  { id: "james_horner", name: "James Horner", roles: ["Composer"], image: IMG },
  { id: "r_d_burman", name: "R. D. Burman", roles: ["Composer"], image: IMG },
  { id: "david_julyan", name: "David Julyan", roles: ["Composer"], image: IMG },
  { id: "gustavo_santaolalla", name: "Gustavo Santaolalla", roles: ["Composer"], image: IMG },
  { id: "joe_hisaishi", name: "Joe Hisaishi", roles: ["Composer"], image: IMG },
  { id: "ed_cortes", name: "Ed Cortês", roles: ["Composer"], image: IMG },
  { id: "antonio_pinto", name: "Antonio Pinto", roles: ["Composer"], image: IMG },
  { id: "cho_young_wuk", name: "Cho Young-wuk", roles: ["Composer"], image: IMG },
  { id: "jon_brion", name: "Jon Brion", roles: ["Composer"], image: IMG },
  { id: "james_newton_howard", name: "James Newton Howard", roles: ["Composer"], image: IMG },
  { id: "javier_navarrete", name: "Javier Navarrete", roles: ["Composer"], image: IMG },
  { id: "carter_burwell", name: "Carter Burwell", roles: ["Composer"], image: IMG },
  { id: "jonny_greenwood", name: "Jonny Greenwood", roles: ["Composer"], image: IMG },
  { id: "a_r_rahman", name: "A. R. Rahman", roles: ["Composer"], image: IMG },
  { id: "gabriel_yared", name: "Gabriel Yared", roles: ["Composer"], image: IMG },
  { id: "stephane_moucha", name: "Stéphane Moucha", roles: ["Composer"], image: IMG },
  { id: "michael_giacchino", name: "Michael Giacchino", roles: ["Composer"], image: IMG },
  { id: "randy_newman", name: "Randy Newman", roles: ["Composer"], image: IMG },
  { id: "clint_mansell", name: "Clint Mansell", roles: ["Composer"], image: IMG },
  { id: "sattar_oraki", name: "Sattar Oraki", roles: ["Composer"], image: IMG },
  { id: "cliff_martinez", name: "Cliff Martinez", roles: ["Composer"], image: IMG },
  { id: "ludovico_einaudi", name: "Ludovico Einaudi", roles: ["Composer"], image: IMG },
  { id: "mychael_danna", name: "Mychael Danna", roles: ["Composer"], image: IMG },
  { id: "steven_price", name: "Steven Price", roles: ["Composer"], image: IMG },
  { id: "justin_hurwitz", name: "Justin Hurwitz", roles: ["Composer"], image: IMG },
  { id: "antonio_sanchez", name: "Antonio Sánchez", roles: ["Composer"], image: IMG },
  { id: "junkie_xl", name: "Junkie XL", roles: ["Composer"], image: IMG },
  { id: "ryuichi_sakamoto", name: "Ryuichi Sakamoto", roles: ["Composer"], image: IMG },
  { id: "alva_noto", name: "Alva Noto", roles: ["Composer"], image: IMG },
  { id: "bryce_dessner", name: "Bryce Dessner", roles: ["Composer"], image: IMG },
  { id: "johann_johannsson", name: "Jóhann Jóhannsson", roles: ["Composer"], image: IMG },
  { id: "lesley_barber", name: "Lesley Barber", roles: ["Composer"], image: IMG },
  { id: "michael_abels", name: "Michael Abels", roles: ["Composer"], image: IMG },
  { id: "benjamin_wallfisch", name: "Benjamin Wallfisch", roles: ["Composer"], image: IMG },
  { id: "marco_beltrami", name: "Marco Beltrami", roles: ["Composer"], image: IMG },
  { id: "daniel_pemberton", name: "Daniel Pemberton", roles: ["Composer"], image: IMG },
  { id: "jung_jae_il", name: "Jung Jae-il", roles: ["Composer"], image: IMG },
  { id: "hildur_gudnadottir", name: "Hildur Guðnadóttir", roles: ["Composer"], image: IMG },
  { id: "trent_reznor", name: "Trent Reznor", roles: ["Composer"], image: IMG },
  { id: "atticus_ross", name: "Atticus Ross", roles: ["Composer"], image: IMG },
  { id: "emile_mosseri", name: "Emile Mosseri", roles: ["Composer"], image: IMG },
  { id: "son_lux", name: "Son Lux", roles: ["Composer"], image: IMG },
  { id: "harold_faltermeyer", name: "Harold Faltermeyer", roles: ["Composer"], image: IMG },
  { id: "lady_gaga", name: "Lady Gaga", roles: ["Composer", "Singer"], image: IMG },
  { id: "lorne_balfe", name: "Lorne Balfe", roles: ["Composer"], image: IMG },
  { id: "volker_bertelmann", name: "Volker Bertelmann", roles: ["Composer"], image: IMG },
  { id: "ludwig_goransson", name: "Ludwig Göransson", roles: ["Composer"], image: IMG },
  { id: "christopher_bear", name: "Christopher Bear", roles: ["Composer"], image: IMG },
  { id: "daniel_rossen", name: "Daniel Rossen", roles: ["Composer"], image: IMG },
  { id: "jerskin_fendrix", name: "Jerskin Fendrix", roles: ["Composer"], image: IMG },
  { id: "mark_ronson", name: "Mark Ronson", roles: ["Composer"], image: IMG },
  { id: "andrew_wyatt", name: "Andrew Wyatt", roles: ["Composer"], image: IMG },
  { id: "raffertie", name: "Raffertie", roles: ["Composer"], image: IMG },
  { id: "shankar_ehsaan_loy", name: "Shankar-Ehsaan-Loy", roles: ["Composer"], image: IMG },
  { id: "jatin_lalit", name: "Jatin-Lalit", roles: ["Composer"], image: IMG },
  { id: "naushad", name: "Naushad", roles: ["Composer"], image: IMG },
  { id: "shantanu_moitra", name: "Shantanu Moitra", roles: ["Composer"], image: IMG },
  { id: "pritam", name: "Pritam", roles: ["Composer"], image: IMG },
  { id: "m_m_keeravani", name: "M. M. Keeravani", roles: ["Composer"], image: IMG },
  { id: "ravi_basrur", name: "Ravi Basrur", roles: ["Composer"], image: IMG },
  { id: "b_ajaneesh_loknath", name: "B. Ajaneesh Loknath", roles: ["Composer"], image: IMG },
  { id: "anirudh_ravichander", name: "Anirudh Ravichander", roles: ["Composer"], image: IMG },
  { id: "satchith_paulose", name: "Satchith Paulose", roles: ["Composer"], image: IMG },
  { id: "ismail_darbar", name: "Ismail Darbar", roles: ["Composer"], image: IMG },
  { id: "tan_dun", name: "Tan Dun", roles: ["Composer"], image: IMG },
  { id: "yann_tiersen", name: "Yann Tiersen", roles: ["Composer"], image: IMG },
  { id: "nikolaj_egelund", name: "Nikolaj Egelund", roles: ["Composer"], image: IMG },
  { id: "lele_marchitelli", name: "Lele Marchitelli", roles: ["Composer"], image: IMG },
  { id: "laszlo_melis", name: "László Melis", roles: ["Composer"], image: IMG },
  { id: "khaled_mouzanar", name: "Khaled Mouzanar", roles: ["Composer", "Writer"], image: IMG },
  { id: "eiko_ishibashi", name: "Eiko Ishibashi", roles: ["Composer"], image: IMG },

  // ── ACTORS ────────────────────────────────────────────────────────────────
  { id: "robert_pattinson", name: "Robert Pattinson", roles: ["Actor"], image: IMG },
  { id: "zendaya", name: "Zendaya", roles: ["Actor"], image: IMG },
  { id: "anne_hathaway", name: "Anne Hathaway", roles: ["Actor"], image: IMG },
  { id: "timothee_chalamet", name: "Timothée Chalamet", roles: ["Actor"], image: IMG },
  { id: "florence_pugh", name: "Florence Pugh", roles: ["Actor"], image: IMG },
  { id: "marlon_brando", name: "Marlon Brando", roles: ["Actor"], image: IMG },
  { id: "al_pacino", name: "Al Pacino", roles: ["Actor"], image: IMG },
  { id: "james_caan", name: "James Caan", roles: ["Actor"], image: IMG },
  { id: "liam_neeson", name: "Liam Neeson", roles: ["Actor"], image: IMG },
  { id: "ben_kingsley", name: "Ben Kingsley", roles: ["Actor"], image: IMG },
  { id: "ralph_fiennes", name: "Ralph Fiennes", roles: ["Actor"], image: IMG },
  { id: "tim_robbins", name: "Tim Robbins", roles: ["Actor"], image: IMG },
  { id: "morgan_freeman", name: "Morgan Freeman", roles: ["Actor"], image: IMG },
  { id: "bob_gunton", name: "Bob Gunton", roles: ["Actor"], image: IMG },
  { id: "tom_hanks", name: "Tom Hanks", roles: ["Actor"], image: IMG },
  { id: "robin_wright", name: "Robin Wright", roles: ["Actor"], image: IMG },
  { id: "gary_sinise", name: "Gary Sinise", roles: ["Actor"], image: IMG },
  { id: "john_travolta", name: "John Travolta", roles: ["Actor"], image: IMG },
  { id: "samuel_l_jackson", name: "Samuel L. Jackson", roles: ["Actor"], image: IMG },
  { id: "uma_thurman", name: "Uma Thurman", roles: ["Actor"], image: IMG },
  { id: "jodie_foster", name: "Jodie Foster", roles: ["Actor"], image: IMG },
  { id: "anthony_hopkins", name: "Anthony Hopkins", roles: ["Actor"], image: IMG },
  { id: "scott_glenn", name: "Scott Glenn", roles: ["Actor"], image: IMG },
  { id: "ray_liotta", name: "Ray Liotta", roles: ["Actor"], image: IMG },
  { id: "robert_de_niro", name: "Robert De Niro", roles: ["Actor"], image: IMG },
  { id: "joe_pesci", name: "Joe Pesci", roles: ["Actor"], image: IMG },
  { id: "brad_pitt", name: "Brad Pitt", roles: ["Actor"], image: IMG },
  { id: "edward_norton", name: "Edward Norton", roles: ["Actor"], image: IMG },
  { id: "helena_bonham_carter", name: "Helena Bonham Carter", roles: ["Actor"], image: IMG },
  { id: "keanu_reeves", name: "Keanu Reeves", roles: ["Actor"], image: IMG },
  { id: "laurence_fishburne", name: "Laurence Fishburne", roles: ["Actor"], image: IMG },
  { id: "carrie_anne_moss", name: "Carrie-Anne Moss", roles: ["Actor"], image: IMG },
  { id: "leonardo_dicaprio", name: "Leonardo DiCaprio", roles: ["Actor"], image: IMG },
  { id: "kate_winslet", name: "Kate Winslet", roles: ["Actor"], image: IMG },
  { id: "billy_zane", name: "Billy Zane", roles: ["Actor"], image: IMG },
  { id: "sam_neill", name: "Sam Neill", roles: ["Actor"], image: IMG },
  { id: "laura_dern", name: "Laura Dern", roles: ["Actor"], image: IMG },
  { id: "jeff_goldblum", name: "Jeff Goldblum", roles: ["Actor"], image: IMG },
  { id: "keir_dullea", name: "Keir Dullea", roles: ["Actor"], image: IMG },
  { id: "gary_lockwood", name: "Gary Lockwood", roles: ["Actor"], image: IMG },
  { id: "william_sylvester", name: "William Sylvester", roles: ["Actor"], image: IMG },
  { id: "russell_crowe", name: "Russell Crowe", roles: ["Actor"], image: IMG },
  { id: "joaquin_phoenix", name: "Joaquin Phoenix", roles: ["Actor"], image: IMG },
  { id: "connie_nielsen", name: "Connie Nielsen", roles: ["Actor"], image: IMG },
  { id: "matthew_broderick", name: "Matthew Broderick", roles: ["Actor"], image: IMG },
  { id: "jeremy_irons", name: "Jeremy Irons", roles: ["Actor"], image: IMG },
  { id: "james_earl_jones", name: "James Earl Jones", roles: ["Actor"], image: IMG },
  { id: "dharmendra", name: "Dharmendra", roles: ["Actor"], image: IMG },
  { id: "amitabh_bachchan", name: "Amitabh Bachchan", roles: ["Actor"], image: IMG },
  { id: "sanjeev_kumar", name: "Sanjeev Kumar", roles: ["Actor"], image: IMG },
  { id: "guy_pearce", name: "Guy Pearce", roles: ["Actor"], image: IMG },
  { id: "joe_pantoliano", name: "Joe Pantoliano", roles: ["Actor"], image: IMG },
  { id: "emilio_echevarria", name: "Emilio Echevarría", roles: ["Actor"], image: IMG },
  { id: "gael_garcia_bernal", name: "Gael García Bernal", roles: ["Actor"], image: IMG },
  { id: "goya_toledo", name: "Goya Toledo", roles: ["Actor"], image: IMG },
  { id: "elijah_wood", name: "Elijah Wood", roles: ["Actor"], image: IMG },
  { id: "ian_mckellen", name: "Ian McKellen", roles: ["Actor"], image: IMG },
  { id: "viggo_mortensen", name: "Viggo Mortensen", roles: ["Actor"], image: IMG },
  { id: "ed_harris", name: "Ed Harris", roles: ["Actor"], image: IMG },
  { id: "jennifer_connelly", name: "Jennifer Connelly", roles: ["Actor"], image: IMG },
  { id: "daveigh_chase", name: "Daveigh Chase", roles: ["Actor"], image: IMG },
  { id: "suzanne_pleshette", name: "Suzanne Pleshette", roles: ["Actor"], image: IMG },
  { id: "susan_egan", name: "Susan Egan", roles: ["Actor"], image: IMG },
  { id: "alexandre_rodrigues", name: "Alexandre Rodrigues", roles: ["Actor"], image: IMG },
  { id: "leandro_firmino", name: "Leandro Firmino", roles: ["Actor"], image: IMG },
  { id: "phellipe_haagensen", name: "Phellipe Haagensen", roles: ["Actor"], image: IMG },
  { id: "christopher_walken", name: "Christopher Walken", roles: ["Actor"], image: IMG },
  { id: "choi_min_sik", name: "Choi Min-sik", roles: ["Actor"], image: IMG },
  { id: "yu_ji_tae", name: "Yu Ji-tae", roles: ["Actor"], image: IMG },
  { id: "kang_hye_jeong", name: "Kang Hye-jeong", roles: ["Actor"], image: IMG },
  { id: "jim_carrey", name: "Jim Carrey", roles: ["Actor"], image: IMG },
  { id: "tom_wilkinson", name: "Tom Wilkinson", roles: ["Actor"], image: IMG },
  { id: "hilary_swank", name: "Hilary Swank", roles: ["Actor"], image: IMG },
  { id: "christian_bale", name: "Christian Bale", roles: ["Actor"], image: IMG },
  { id: "michael_caine", name: "Michael Caine", roles: ["Actor"], image: IMG },
  { id: "heath_ledger", name: "Heath Ledger", roles: ["Actor"], image: IMG },
  { id: "jake_gyllenhaal", name: "Jake Gyllenhaal", roles: ["Actor"], image: IMG },
  { id: "michelle_williams", name: "Michelle Williams", roles: ["Actor"], image: IMG },
  { id: "ivana_baquero", name: "Ivana Baquero", roles: ["Actor"], image: IMG },
  { id: "sergi_lopez", name: "Sergi López", roles: ["Actor"], image: IMG },
  { id: "maribel_verdu", name: "Maribel Verdú", roles: ["Actor"], image: IMG },
  { id: "matt_damon", name: "Matt Damon", roles: ["Actor"], image: IMG },
  { id: "jack_nicholson", name: "Jack Nicholson", roles: ["Actor"], image: IMG },
  { id: "hugh_jackman", name: "Hugh Jackman", roles: ["Actor"], image: IMG },
  { id: "scarlett_johansson", name: "Scarlett Johansson", roles: ["Actor"], image: IMG },
  { id: "tommy_lee_jones", name: "Tommy Lee Jones", roles: ["Actor"], image: IMG },
  { id: "javier_bardem", name: "Javier Bardem", roles: ["Actor"], image: IMG },
  { id: "josh_brolin", name: "Josh Brolin", roles: ["Actor"], image: IMG },
  { id: "daniel_day_lewis", name: "Daniel Day-Lewis", roles: ["Actor"], image: IMG },
  { id: "paul_dano", name: "Paul Dano", roles: ["Actor"], image: IMG },
  { id: "dillon_freasier", name: "Dillon Freasier", roles: ["Actor"], image: IMG },
  { id: "aaron_eckhart", name: "Aaron Eckhart", roles: ["Actor"], image: IMG },
  { id: "dev_patel", name: "Dev Patel", roles: ["Actor"], image: IMG },
  { id: "freida_pinto", name: "Freida Pinto", roles: ["Actor"], image: IMG },
  { id: "madhur_mittal", name: "Madhur Mittal", roles: ["Actor"], image: IMG },
  { id: "ulrich_muhe", name: "Ulrich Mühe", roles: ["Actor"], image: IMG },
  { id: "martina_gedeck", name: "Martina Gedeck", roles: ["Actor"], image: IMG },
  { id: "sebastian_koch", name: "Sebastian Koch", roles: ["Actor"], image: IMG },
  { id: "edward_asner", name: "Edward Asner", roles: ["Actor"], image: IMG },
  { id: "jordan_nagai", name: "Jordan Nagai", roles: ["Actor"], image: IMG },
  { id: "sam_worthington", name: "Sam Worthington", roles: ["Actor"], image: IMG },
  { id: "zoe_saldana", name: "Zoe Saldana", roles: ["Actor"], image: IMG },
  { id: "sigourney_weaver", name: "Sigourney Weaver", roles: ["Actor"], image: IMG },
  { id: "joseph_gordon_levitt", name: "Joseph Gordon-Levitt", roles: ["Actor"], image: IMG },
  { id: "elliot_page", name: "Elliot Page", roles: ["Actor"], image: IMG },
  { id: "tim_allen", name: "Tim Allen", roles: ["Actor"], image: IMG },
  { id: "joan_cusack", name: "Joan Cusack", roles: ["Actor"], image: IMG },
  { id: "natalie_portman", name: "Natalie Portman", roles: ["Actor"], image: IMG },
  { id: "mila_kunis", name: "Mila Kunis", roles: ["Actor"], image: IMG },
  { id: "vincent_cassel", name: "Vincent Cassel", roles: ["Actor"], image: IMG },
  { id: "peyman_moaadi", name: "Peyman Moaadi", roles: ["Actor"], image: IMG },
  { id: "leila_hatami", name: "Leila Hatami", roles: ["Actor"], image: IMG },
  { id: "sareh_bayat", name: "Sareh Bayat", roles: ["Actor"], image: IMG },
  { id: "ryan_gosling", name: "Ryan Gosling", roles: ["Actor"], image: IMG },
  { id: "carey_mulligan", name: "Carey Mulligan", roles: ["Actor"], image: IMG },
  { id: "bryan_cranston", name: "Bryan Cranston", roles: ["Actor"], image: IMG },
  { id: "francois_cluzet", name: "François Cluzet", roles: ["Actor"], image: IMG },
  { id: "omar_sy", name: "Omar Sy", roles: ["Actor"], image: IMG },
  { id: "anne_le_ny", name: "Anne Le Ny", roles: ["Actor"], image: IMG },
  { id: "jamie_foxx", name: "Jamie Foxx", roles: ["Actor"], image: IMG },
  { id: "christoph_waltz", name: "Christoph Waltz", roles: ["Actor"], image: IMG },
  { id: "tom_hardy", name: "Tom Hardy", roles: ["Actor"], image: IMG },
  { id: "suraj_sharma", name: "Suraj Sharma", roles: ["Actor"], image: IMG },
  { id: "irrfan_khan", name: "Irrfan Khan", roles: ["Actor"], image: IMG },
  { id: "rafe_spall", name: "Rafe Spall", roles: ["Actor"], image: IMG },
  { id: "sandra_bullock", name: "Sandra Bullock", roles: ["Actor"], image: IMG },
  { id: "george_clooney", name: "George Clooney", roles: ["Actor"], image: IMG },
  { id: "chiwetel_ejiofor", name: "Chiwetel Ejiofor", roles: ["Actor"], image: IMG },
  { id: "michael_fassbender", name: "Michael Fassbender", roles: ["Actor"], image: IMG },
  { id: "lupita_nyongo", name: "Lupita Nyong'o", roles: ["Actor"], image: IMG },
  { id: "jonah_hill", name: "Jonah Hill", roles: ["Actor"], image: IMG },
  { id: "margot_robbie", name: "Margot Robbie", roles: ["Actor"], image: IMG },
  { id: "matthew_mcconaughey", name: "Matthew McConaughey", roles: ["Actor"], image: IMG },
  { id: "jessica_chastain", name: "Jessica Chastain", roles: ["Actor"], image: IMG },
  { id: "miles_teller", name: "Miles Teller", roles: ["Actor"], image: IMG },
  { id: "j_k_simmons", name: "J. K. Simmons", roles: ["Actor"], image: IMG },
  { id: "paul_reiser", name: "Paul Reiser", roles: ["Actor"], image: IMG },
  { id: "michael_keaton", name: "Michael Keaton", roles: ["Actor"], image: IMG },
  { id: "emma_stone", name: "Emma Stone", roles: ["Actor"], image: IMG },
  { id: "charlize_theron", name: "Charlize Theron", roles: ["Actor"], image: IMG },
  { id: "nicholas_hoult", name: "Nicholas Hoult", roles: ["Actor"], image: IMG },
  { id: "will_poulter", name: "Will Poulter", roles: ["Actor"], image: IMG },
  { id: "john_legend", name: "John Legend", roles: ["Actor"], image: IMG },
  { id: "amy_adams", name: "Amy Adams", roles: ["Actor"], image: IMG },
  { id: "jeremy_renner", name: "Jeremy Renner", roles: ["Actor"], image: IMG },
  { id: "forest_whitaker", name: "Forest Whitaker", roles: ["Actor"], image: IMG },
  { id: "casey_affleck", name: "Casey Affleck", roles: ["Actor"], image: IMG },
  { id: "kyle_chandler", name: "Kyle Chandler", roles: ["Actor"], image: IMG },
  { id: "daniel_kaluuya", name: "Daniel Kaluuya", roles: ["Actor"], image: IMG },
  { id: "allison_williams", name: "Allison Williams", roles: ["Actor"], image: IMG },
  { id: "bradley_whitford", name: "Bradley Whitford", roles: ["Actor"], image: IMG },
  { id: "fionn_whitehead", name: "Fionn Whitehead", roles: ["Actor"], image: IMG },
  { id: "mark_rylance", name: "Mark Rylance", roles: ["Actor"], image: IMG },
  { id: "harrison_ford", name: "Harrison Ford", roles: ["Actor"], image: IMG },
  { id: "ana_de_armas", name: "Ana de Armas", roles: ["Actor"], image: IMG },
  { id: "anthony_gonzalez", name: "Anthony Gonzalez", roles: ["Actor"], image: IMG },
  { id: "benjamin_bratt", name: "Benjamin Bratt", roles: ["Actor"], image: IMG },
  { id: "emily_blunt", name: "Emily Blunt", roles: ["Actor"], image: IMG },
  { id: "millicent_simmonds", name: "Millicent Simmonds", roles: ["Actor"], image: IMG },
  { id: "yalitza_aparicio", name: "Yalitza Aparicio", roles: ["Actor"], image: IMG },
  { id: "marina_de_tavira", name: "Marina de Tavira", roles: ["Actor"], image: IMG },
  { id: "fernando_grediaga", name: "Fernando Grediaga", roles: ["Actor"], image: IMG },
  { id: "shameik_moore", name: "Shameik Moore", roles: ["Actor"], image: IMG },
  { id: "jake_johnson", name: "Jake Johnson", roles: ["Actor"], image: IMG },
  { id: "hailee_steinfeld", name: "Hailee Steinfeld", roles: ["Actor"], image: IMG },
  { id: "robert_downey_jr", name: "Robert Downey Jr.", roles: ["Actor"], image: IMG },
  { id: "chris_evans", name: "Chris Evans", roles: ["Actor"], image: IMG },
  { id: "mark_ruffalo", name: "Mark Ruffalo", roles: ["Actor"], image: IMG },
  { id: "song_kang_ho", name: "Song Kang-ho", roles: ["Actor"], image: IMG },
  { id: "lee_sun_kyun", name: "Lee Sun-kyun", roles: ["Actor"], image: IMG },
  { id: "cho_yeo_jeong", name: "Cho Yeo-jeong", roles: ["Actor"], image: IMG },
  { id: "zazie_beetz", name: "Zazie Beetz", roles: ["Actor"], image: IMG },
  { id: "frances_conroy", name: "Frances Conroy", roles: ["Actor"], image: IMG },
  { id: "emile_hirsch", name: "Emile Hirsch", roles: ["Actor"], image: IMG },
  { id: "tina_fey", name: "Tina Fey", roles: ["Actor"], image: IMG },
  { id: "graham_norton", name: "Graham Norton", roles: ["Actor"], image: IMG },
  { id: "steven_yeun", name: "Steven Yeun", roles: ["Actor"], image: IMG },
  { id: "han_ye_ri", name: "Han Ye-ri", roles: ["Actor"], image: IMG },
  { id: "alan_kim", name: "Alan Kim", roles: ["Actor"], image: IMG },
  { id: "oscar_isaac", name: "Oscar Isaac", roles: ["Actor"], image: IMG },
  { id: "rebecca_ferguson", name: "Rebecca Ferguson", roles: ["Actor"], image: IMG },
  { id: "benedict_cumberbatch", name: "Benedict Cumberbatch", roles: ["Actor"], image: IMG },
  { id: "kirsten_dunst", name: "Kirsten Dunst", roles: ["Actor"], image: IMG },
  { id: "jesse_plemons", name: "Jesse Plemons", roles: ["Actor"], image: IMG },
  { id: "tom_holland", name: "Tom Holland", roles: ["Actor"], image: IMG },
  { id: "tobey_maguire", name: "Tobey Maguire", roles: ["Actor"], image: IMG },
  { id: "michelle_yeoh", name: "Michelle Yeoh", roles: ["Actor"], image: IMG },
  { id: "ke_huy_quan", name: "Ke Huy Quan", roles: ["Actor"], image: IMG },
  { id: "jamie_lee_curtis", name: "Jamie Lee Curtis", roles: ["Actor"], image: IMG },
  { id: "tom_cruise", name: "Tom Cruise", roles: ["Actor", "Producer"], image: IMG },
  { id: "colin_farrell", name: "Colin Farrell", roles: ["Actor"], image: IMG },
  { id: "brendan_gleeson", name: "Brendan Gleeson", roles: ["Actor"], image: IMG },
  { id: "barry_keoghan", name: "Barry Keoghan", roles: ["Actor"], image: IMG },
  { id: "felix_kammerer", name: "Felix Kammerer", roles: ["Actor"], image: IMG },
  { id: "albrecht_schuch", name: "Albrecht Schuch", roles: ["Actor"], image: IMG },
  { id: "aaron_hilmer", name: "Aaron Hilmer", roles: ["Actor"], image: IMG },
  { id: "greta_lee", name: "Greta Lee", roles: ["Actor"], image: IMG },
  { id: "teo_yoo", name: "Teo Yoo", roles: ["Actor"], image: IMG },
  { id: "john_magaro", name: "John Magaro", roles: ["Actor"], image: IMG },
  { id: "willem_dafoe", name: "Willem Dafoe", roles: ["Actor"], image: IMG },
  { id: "america_ferrera", name: "America Ferrera", roles: ["Actor"], image: IMG },
  { id: "simu_liu", name: "Simu Liu", roles: ["Actor"], image: IMG },
  { id: "austin_butler", name: "Austin Butler", roles: ["Actor"], image: IMG },
  { id: "demi_moore", name: "Demi Moore", roles: ["Actor"], image: IMG },
  { id: "margaret_qualley", name: "Margaret Qualley", roles: ["Actor"], image: IMG },
  { id: "dennis_quaid", name: "Dennis Quaid", roles: ["Actor"], image: IMG },
  { id: "stanley_tucci", name: "Stanley Tucci", roles: ["Actor"], image: IMG },
  { id: "john_lithgow", name: "John Lithgow", roles: ["Actor"], image: IMG },
  { id: "gracy_singh", name: "Gracy Singh", roles: ["Actor"], image: IMG },
  { id: "rachel_shelley", name: "Rachel Shelley", roles: ["Actor"], image: IMG },
  { id: "saif_ali_khan", name: "Saif Ali Khan", roles: ["Actor"], image: IMG },
  { id: "akshaye_khanna", name: "Akshaye Khanna", roles: ["Actor"], image: IMG },
  { id: "shah_rukh_khan", name: "Shah Rukh Khan", roles: ["Actor"], image: IMG },
  { id: "kajol", name: "Kajol", roles: ["Actor"], image: IMG },
  { id: "amrish_puri", name: "Amrish Puri", roles: ["Actor"], image: IMG },
  { id: "prithviraj_kapoor", name: "Prithviraj Kapoor", roles: ["Actor"], image: IMG },
  { id: "dilip_kumar", name: "Dilip Kumar", roles: ["Actor"], image: IMG },
  { id: "madhubala", name: "Madhubala", roles: ["Actor"], image: IMG },
  { id: "madhavan", name: "Madhavan", roles: ["Actor"], image: IMG },
  { id: "sharman_joshi", name: "Sharman Joshi", roles: ["Actor"], image: IMG },
  { id: "anushka_sharma", name: "Anushka Sharma", roles: ["Actor"], image: IMG },
  { id: "sushant_singh_rajput", name: "Sushant Singh Rajput", roles: ["Actor"], image: IMG },
  { id: "fatima_sana_shaikh", name: "Fatima Sana Shaikh", roles: ["Actor"], image: IMG },
  { id: "sanya_malhotra", name: "Sanya Malhotra", roles: ["Actor"], image: IMG },
  { id: "prabhas", name: "Prabhas", roles: ["Actor"], image: IMG },
  { id: "rana_daggubati", name: "Rana Daggubati", roles: ["Actor"], image: IMG },
  { id: "anushka_shetty", name: "Anushka Shetty", roles: ["Actor"], image: IMG },
  { id: "darsheel_safary", name: "Darsheel Safary", roles: ["Actor"], image: IMG },
  { id: "tisca_chopra", name: "Tisca Chopra", roles: ["Actor"], image: IMG },
  { id: "n_t_rama_rao_jr", name: "N. T. Rama Rao Jr.", roles: ["Actor"], image: IMG },
  { id: "ram_charan", name: "Ram Charan", roles: ["Actor"], image: IMG },
  { id: "alia_bhatt", name: "Alia Bhatt", roles: ["Actor"], image: IMG },
  { id: "yash", name: "Yash", roles: ["Actor"], image: IMG },
  { id: "sanjay_dutt", name: "Sanjay Dutt", roles: ["Actor"], image: IMG },
  { id: "raveena_tandon", name: "Raveena Tandon", roles: ["Actor"], image: IMG },
  { id: "sapthami_gowda", name: "Sapthami Gowda", roles: ["Actor"], image: IMG },
  { id: "kishore", name: "Kishore", roles: ["Actor"], image: IMG },
  { id: "nayanthara", name: "Nayanthara", roles: ["Actor"], image: IMG },
  { id: "vijay_sethupathi", name: "Vijay Sethupathi", roles: ["Actor"], image: IMG },
  { id: "ayushmann_khurrana", name: "Ayushmann Khurrana", roles: ["Actor"], image: IMG },
  { id: "tabu", name: "Tabu", roles: ["Actor"], image: IMG },
  { id: "radhika_apte", name: "Radhika Apte", roles: ["Actor"], image: IMG },
  { id: "ranveer_singh", name: "Ranveer Singh", roles: ["Actor"], image: IMG },
  { id: "siddhant_chaturvedi", name: "Siddhant Chaturvedi", roles: ["Actor"], image: IMG },
  { id: "aishwarya_rai", name: "Aishwarya Rai", roles: ["Actor"], image: IMG },
  { id: "madhuri_dixit", name: "Madhuri Dixit", roles: ["Actor"], image: IMG },
  { id: "chow_yun_fat", name: "Chow Yun-fat", roles: ["Actor"], image: IMG },
  { id: "zhang_ziyi", name: "Zhang Ziyi", roles: ["Actor"], image: IMG },
  { id: "audrey_tautou", name: "Audrey Tautou", roles: ["Actor"], image: IMG },
  { id: "mathieu_kassovitz", name: "Mathieu Kassovitz", roles: ["Actor"], image: IMG },
  { id: "rufus", name: "Rufus", roles: ["Actor"], image: IMG },
  { id: "mads_mikkelsen", name: "Mads Mikkelsen", roles: ["Actor"], image: IMG },
  { id: "thomas_bo_larsen", name: "Thomas Bo Larsen", roles: ["Actor"], image: IMG },
  { id: "annika_wedderkopp", name: "Annika Wedderkopp", roles: ["Actor"], image: IMG },
  { id: "toni_servillo", name: "Toni Servillo", roles: ["Actor"], image: IMG },
  { id: "carlo_verdone", name: "Carlo Verdone", roles: ["Actor"], image: IMG },
  { id: "sabrina_ferilli", name: "Sabrina Ferilli", roles: ["Actor"], image: IMG },
  { id: "geza_rohrig", name: "Géza Röhrig", roles: ["Actor"], image: IMG },
  { id: "levente_molnar", name: "Levente Molnár", roles: ["Actor"], image: IMG },
  { id: "urs_rechn", name: "Urs Rechn", roles: ["Actor"], image: IMG },
  { id: "claes_bang", name: "Claes Bang", roles: ["Actor"], image: IMG },
  { id: "elisabeth_moss", name: "Elisabeth Moss", roles: ["Actor"], image: IMG },
  { id: "dominic_west", name: "Dominic West", roles: ["Actor"], image: IMG },
  { id: "zain_al_rafeea", name: "Zain Al Rafeea", roles: ["Actor"], image: IMG },
  { id: "yordanos_shiferaw", name: "Yordanos Shiferaw", roles: ["Actor"], image: IMG },
  { id: "boluwatife_treasure_bankole", name: "Boluwatife Treasure Bankole", roles: ["Actor"], image: IMG },
  { id: "hidetoshi_nishijima", name: "Hidetoshi Nishijima", roles: ["Actor"], image: IMG },
  { id: "toko_miura", name: "Tôko Miura", roles: ["Actor"], image: IMG },
  { id: "reika_kirishima", name: "Reika Kirishima", roles: ["Actor"], image: IMG }
];